import { defineTheme } from "../components/ui/theme";

/** Generated by Balsa UI. Edit this definition in your application. */
export const myDesignSystemTheme = defineTheme({
  "id": "my-design-system",
  "name": "My Design System",
  "extends": "modern-flat",
  "options": {
    "spacing": "tight",
    "material": "solid"
  },
  "overrides": {
    "tokens": {
      "typography": {
        "bodyFonts": [
          "Pretendard",
          "sans-serif"
        ],
        "controlFonts": [
          "Pretendard",
          "sans-serif"
        ],
        "titleFonts": [
          "Pretendard",
          "sans-serif"
        ],
        "controlWeight": 500,
        "titleLetterSpacing": -1
      },
      "radius": {
        "control": 4,
        "surface": 7,
        "panel": 9,
        "badge": 9999,
        "toggle": 9999,
        "codeControl": 4
      }
    }
  }
});
