import fs from "node:fs";
import assert from "node:assert/strict";
import { createClient } from "@supabase/supabase-js";
import { newsPost } from "../lib/news-record.ts";
import { editorialSchema } from "../lib/news-editorial.ts";
process.loadEnvFile(".env.local");
const db = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL, process.env.SUPABASE_SERVICE_ROLE_KEY, { auth: { persistSession: false, autoRefreshToken: false } });
const articles = JSON.parse(fs.readFileSync("content/news/initial-articles.json", "utf8"));
for (const article of articles) editorialSchema.parse({ url: article.url, title: article.title, summary: article.summary, paragraphs: article.paragraphs, points: article.points, tags: article.tags });
const rows = articles.map(newsPost);
const admins = await db.from("users").select("id,name").eq("role", "admin").limit(20);
if (admins.error) throw new Error(admins.error.message);
const brandEditors = admins.data.filter(editor => ["ARCH-B", "ARCH.B"].includes(editor.name));
const authorId = process.env.ARCHB_NEWS_AUTHOR_ID || (brandEditors.length === 1 ? brandEditors[0].id : admins.data.length === 1 ? admins.data[0].id : null);
assert.ok(authorId, "Set ARCHB_NEWS_AUTHOR_ID to an existing ARCH.B editor when multiple admins exist");
for (const row of rows) row.author_id = authorId;
const existing = await db.from("posts").select("slug,type").in("slug", rows.map(row => row.slug));
if (existing.error) throw new Error(existing.error.message);
assert.ok(existing.data.every(row => row.type === "news"), "A news slug overlaps an existing non-news post");
const saved = await db.from("posts").upsert(rows, { onConflict: "slug", ignoreDuplicates: true }).select("id");
if (saved.error) throw new Error(saved.error.message);
const publicDb = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL, process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY, { auth: { persistSession: false } });
const publicNews = await publicDb.from("posts").select("slug,title,content").eq("type", "news").eq("is_published", true);
if (publicNews.error) throw new Error(publicNews.error.message);
assert.ok(rows.every(row => publicNews.data.some(post => post.slug === row.slug)));
console.log(JSON.stringify({ inserted: saved.data.length, verifiedPublished: publicNews.data.length }));
